# Generated by Django 2.1.2 on 2018-11-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181031_2000'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.ManyToManyField(blank=True, to='base.Url'),
        ),
    ]
