# Generated by Django 2.1.2 on 2018-11-08 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
