# Generated by Django 2.1.2 on 2018-11-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181116_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start']},
        ),
    ]
