# Generated by Django 2.1.2 on 2018-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181125_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предлагаемая дата'),
        ),
    ]
