# Generated by Django 2.1.2 on 2018-11-25 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181125_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='date',
        ),
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Пожелания'),
        ),
    ]
