# Generated by Django 2.1.2 on 2018-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20181130_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.ManyToManyField(blank=True, to='base.Video'),
        ),
    ]
