# Generated by Django 2.1.2 on 2018-11-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
