# Generated by Django 2.1.2 on 2018-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Электропочта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
    ]
