# Generated by Django 2.1.2 on 2018-11-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('savva3', '0002_settings'), ('savva3', '0003_auto_20181111_2107')]

    dependencies = [
        ('savva3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
