# Generated by Django 2.1.2 on 2018-11-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savva3', '0002_settings_squashed_0003_auto_20181111_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
    ]
