# Generated by Django 2.1.2 on 2018-11-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savva3', '0003_delete_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
