# Generated by Django 2.1.2 on 2018-12-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('jokes.Joke', 'Jokes')], max_length=100, verbose_name='Тип')),
                ('iid', models.IntegerField(verbose_name='Внешний ключ')),
                ('ip', models.CharField(max_length=20, verbose_name='IP адрес')),
                ('value', models.IntegerField(default=1, verbose_name='Голос')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата голосования')),
            ],
        ),
    ]
