INSTALLED_APPS = [
    'pages',
    'base',
    'allmath',
    'django_filters',
    'embed_video',
    'django_extensions',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
