# Generated by Django 2.1.2 on 2018-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytreeitem',
            name='_keywords',
            field=models.TextField(blank=True),
        ),
    ]
