# Generated by Django 2.1.2 on 2018-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0002_mytreeitem__keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytreeitem',
            name='_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
