# Generated by Django 2.1.2 on 2018-11-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0003_auto_20181113_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytreeitem',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
