# Generated by Django 2.1.2 on 2018-11-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0004_auto_20181113_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytreeitem',
            name='head_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mytreeitem',
            name='title',
            field=models.CharField(help_text='Site tree item title. Can contain template variables E.g.: {{ mytitle }}.', max_length=100, verbose_name='Title'),
        ),
    ]
