# Generated by Django 2.1.2 on 2018-11-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0005_auto_20181113_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytreeitem',
            old_name='_keywords',
            new_name='keywords_string',
        ),
    ]
