# Generated by Django 2.1.2 on 2018-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savva_menu', '0006_auto_20181113_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytreeitem',
            name='changefreq',
            field=models.CharField(default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='mytreeitem',
            name='priority',
            field=models.FloatField(default=1),
        ),
    ]
