# Generated by Django 2.1.2 on 2018-10-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
