# Generated by Django 2.1.2 on 2018-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20181028_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='adult',
            field=models.BooleanField(default=False),
        ),
    ]
