# Generated by Django 2.1.2 on 2018-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_joke_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='already_in_book',
            field=models.BooleanField(default=False),
        ),
    ]
