# Generated by Django 2.1.2 on 2018-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_joke_already_in_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='already_in_book',
            field=models.BooleanField(default=False, verbose_name='Уже в книге'),
        ),
    ]
