# Generated by Django 2.1.2 on 2018-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_auto_20181031_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='Кто добавляет'),
        ),
    ]
