# Generated by Django 2.1.2 on 2018-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_auto_20181108_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='joke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='joke',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
