# Generated by Django 2.1.2 on 2018-11-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_auto_20181118_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='_keywords',
            new_name='keywords',
        ),
        migrations.AddField(
            model_name='joke',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
