# Generated by Django 2.1.2 on 2018-12-29 19:50

from django.db import migrations, models

def split_rating(apps, schema_editor):
    Jokes = apps.get_model('jokes', 'Joke')
    Rating = apps.get_model('rating', 'Rating')
    results = Rating.objects\
        .values('rating_type', 'iid')\
        .annotate(
            positive=models.Sum('value', filter=models.Q(value__gt=0)),
            negative=models.Sum('value', filter=models.Q(value__lt=0)),
        )

    for rating in results:
        label, model = rating['rating_type'].split('.')
        Model = apps.get_model(label, model)
        model = Model.objects.get(id=rating['iid'])
        model.rating_positive = rating['positive'] or 0
        model.rating_negative = rating['negative'] or 0
        model.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_joke_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='rating_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joke',
            name='rating_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(split_rating),
    ]
