# Generated by Django 2.1.2 on 2018-10-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='start',
        ),
    ]
