# Generated by Django 2.1.2 on 2018-10-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0004_event_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
