# Generated by Django 2.1.2 on 2018-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0005_event_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
