# Generated by Django 2.1.2 on 2018-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
