# Generated by Django 2.1.2 on 2018-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_url_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
