# Generated by Django 2.1.2 on 2018-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181031_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='urls', to='base.Area', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='url',
            name='many_tag',
            field=models.ManyToManyField(blank=True, related_name='urls', to='base.Tag', verbose_name='Тип'),
        ),
    ]
