# Generated by Django 2.1.2 on 2018-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20181108_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
