# Generated by Django 2.1.2 on 2018-10-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
