# Generated by Django 2.1.2 on 2018-11-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_url_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='keywords_string',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
