# Generated by Django 2.1.2 on 2018-11-12 11:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import meta.models


class Migration(migrations.Migration):

    replaces = [('base', '0008_resource_video'), ('base', '0009_resource_areas'), ('base', '0010_auto_20181112_0140'), ('base', '0011_auto_20181112_0151'), ('base', '0012_resource_authors')]

    dependencies = [
        ('base', '0007_url_keywords_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Resource')),
                ('url', models.URLField(max_length=500, unique=True)),
            ],
            bases=('base.resource',),
        ),
        migrations.AddField(
            model_name='resource',
            name='areas',
            field=models.ManyToManyField(to='base.Area'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Resource')),
            ],
            bases=('base.resource',),
        ),
        migrations.AddField(
            model_name='resource',
            name='_keywords',
            field=models.CharField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='authors',
            field=models.ManyToManyField(to='base.Author'),
        ),
    ]
