# Generated by Django 2.1.2 on 2018-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_resource_video_squashed_0012_resource_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
