# Generated by Django 2.1.2 on 2018-11-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_resource_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='areas',
            field=models.ManyToManyField(to='base.Area'),
        ),
    ]
