# Generated by Django 2.1.2 on 2018-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20181026_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='areas',
            field=models.ManyToManyField(blank=True, to='base.Area'),
        ),
        migrations.AlterField(
            model_name='url',
            name='many_tag',
            field=models.ManyToManyField(blank=True, to='base.Tag'),
        ),
    ]
