# Generated by Django 2.1.2 on 2018-11-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_resource_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
