# Generated by Django 2.1.2 on 2018-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20181026_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='tag',
        ),
        migrations.AlterField(
            model_name='url',
            name='areas',
            field=models.ManyToManyField(blank=True, to='base.Area', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='url',
            name='many_tag',
            field=models.ManyToManyField(blank=True, to='base.Tag', verbose_name='Тип'),
        ),
    ]
