# Generated by Django 2.1.2 on 2018-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20181112_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(choices=[('depends', 'Depends on'), ('refers', 'Refers to')], max_length=20),
        ),
    ]
