# Generated by Django 2.1.2 on 2018-11-16 19:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20181115_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(max_length=500, unique=True),
        ),
    ]
