# Generated by Django 2.1.2 on 2018-11-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulae', models.CharField(max_length=1000)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
