# Generated by Django 2.1.2 on 2018-11-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='counter',
        ),
        migrations.AddField(
            model_name='counter',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
