# Generated by Django 2.1.2 on 2018-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20181115_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
