# Generated by Django 2.1.2 on 2018-10-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMathTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('depends', models.ManyToManyField(related_name='_allmaththeme_depends_+', to='allmath.AllMathTheme')),
            ],
        ),
        migrations.CreateModel(
            name='AllMathVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ytid', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('theme', models.ManyToManyField(to='allmath.AllMathTheme')),
            ],
        ),
    ]
