# Generated by Django 2.1.2 on 2018-10-27 12:59

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMathTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('depends', models.ManyToManyField(blank=True, related_name='_allmaththeme_depends_+', to='allmath.AllMathTheme')),
            ],
        ),
        migrations.CreateModel(
            name='AllMathVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('video', embed_video.fields.EmbedVideoField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('theme', models.ManyToManyField(blank=True, to='allmath.AllMathTheme')),
            ],
        ),
    ]
