# Generated by Django 2.1.2 on 2018-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmaththeme',
            name='depends',
            field=models.ManyToManyField(blank=True, related_name='_allmaththeme_depends_+', to='allmath.AllMathTheme'),
        ),
    ]
