# Generated by Django 2.1.2 on 2018-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmath', '0002_auto_20181027_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmathvideo',
            name='theme',
            field=models.ManyToManyField(blank=True, to='allmath.AllMathTheme'),
        ),
    ]
