# Generated by Django 2.1.2 on 2018-10-27 09:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allmath', '0003_auto_20181027_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmathvideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
