# Generated by Django 2.1.2 on 2018-10-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allmath', '0004_allmathvideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmathvideo',
            name='ytid',
        ),
    ]
