# Generated by Django 2.1.2 on 2018-10-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmath', '0005_remove_allmathvideo_ytid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmathvideo',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
